### PR TITLE
don't create bbox if not specified by user

### PR DESCRIPTION
**Pull request by DomagojKorais**
bbox is not created if the user doesn't specify it.
I modified an already existing test in order to avoid doing too many requests. The modified test is `test_multipart_geometry`, since the results doesn't change from the previous version, where bbox was specified explicitly, I would say that there is no reason to create the bbox.

### CODE REVIEW

**Comment by batic** [comment]
The error message when both `bbox` and `geometry` are not specified should change from `and/or` to just `or`:
```python
        if bbox is None and geometry is None:
            raise ValueError("'bbox' and/or 'geometry' have to be provided.")		            raise ValueError("'bbox' and/or 'geometry' have to be provided.")

```

**Comment by batic** [comment]
Additionally, I would suggest checking if what we retrieve from SH is what we expect, checking  (corner) cases like what happens if we send to SH both bbox and geometry, but bbox only partially covers geometry (or not at all).

Moving these checks to unit-tests would then be appreciated.

**Comment by AleksMat** [comment]
> The error message when both `bbox` and `geometry` are not specified should change from `and/or` to just `or`:
> 
> ```python
>         if bbox is None and geometry is None:
>             raise ValueError("'bbox' and/or 'geometry' have to be provided.")		            raise ValueError("'bbox' and/or 'geometry' have to be provided.")
> ```

Actually, you can still provide both and the service supports that. E.g. you provide a large bbox and a smaller geometry inside and the service should return an image of the entire bbox but with data only inside the geometry.

**Comment by batic** [comment]
> > The error message when both `bbox` and `geometry` are not specified should change from `and/or` to just `or`:
> > ```python
> >         if bbox is None and geometry is None:
> >             raise ValueError("'bbox' and/or 'geometry' have to be provided.")		            raise ValueError("'bbox' and/or 'geometry' have to be provided.")
> > ```
> 
> Actually, you can still provide both and the service supports that. E.g. you provide a large bbox and a smaller geometry inside and the service should return an image of the entire bbox but with data only inside the geometry.

Ah, ok. In that case probably everything is covered by the changes @DomagojKorais has implemented.

**Comment by DomagojKorais** [comment]
> Additionally, I would suggest checking if what we retrieve from SH is what we expect, checking (corner) cases like what happens if we send to SH both bbox and geometry, but bbox only partially covers geometry (or not at all).
> 
> Moving these checks to unit-tests would then be appreciated.

I will implement those additional checks.

**Comment by DomagojKorais** [comment]
I prepared the unit tests, in order to cover all the combinations there are four of them:
* geometry contained into bbox
* bbox and geometry disjoint
* bbox and geometry intersects
* geometry contains bbox

One issue is that for each of them I need to make a new request, so I am not sure if this is optimal, since each request slows down the testing. 
Possible solutions are:
* avoid testing this aspect, since it is managed directly by SH.
* add those tests in other tests, in order to avoid making new requests.

**Comment by AleksMat** [comment]
I think that the purpose of these tests should be that they make sure user parameters are correctly passed to the service and that is done by detecting statistical values in service responses. Therefore I suggest that we don't have tests whose single purpose is to verify that the service itself is working correctly. In the end, we don't want that these tests make to many requests to SH service as this only slows them down.

Cases of how SH service works given different relations between bbox and geometry IMO only test SH service itself. In this issue, I think that we only want to understand how they work but not really add them to tests.

So far almost all tests use only bbox and there is one test that uses geometry and a bbox, which is derived from geometry. My suggestion is that:

- `test_multipart_geometry` derives bbox from geometry. Let's remove bbox from this test and have only geometry.
- Let's add another test with bbox and geometry where these 2 are intersecting.

@batic what is your opinion about this? Would you want to have more tests?

**Comment by batic** [comment]
> @batic what is your opinion about this? Would you want to have more tests?

Yes if we want to have "integration tests". Otherwise, no. 

I agree with your suggestion to have `test_multipart_geometry` just `geometry`, and adding one more example where both `bbox` and `geometry` are given but `bbox` does not completely cover the `geometry`.

**Comment by DomagojKorais** [comment]
* `test_multipart_geometry` now uses only geometry and box is used only to compute the right size.
*  added test for the intersection case.

**Pull request merged**
